/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import imat.controller.UserManager;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import se.chalmers.ait.dat215.project.Customer;

/**
 *
 * @author mats
 */
public class EditProfilePanel extends javax.swing.JPanel implements PropertyChangeListener {
    
    private final UserManager um = UserManager.getInstance();
    
    /**
     * Creates new form EditProfilePanel
     */
    public EditProfilePanel() {
        initComponents();
        um.addPropertyChangeListener(this);
        prefillForm();
    }
    
    private void prefillForm() {
        Customer customer = um.getCustomer();
        
        prenameTextField.setText(customer.getFirstName());
        lastnameTextField.setText(customer.getLastName());
        //persnbrLabel.setText(customer.getPersNbr());
        emailTextField.setText(customer.getEmail());
        phoneTextField.setText(customer.getMobilePhoneNumber());
        adressTextField.setText(customer.getAddress());
        postadressTextField.setText(customer.getPostCode());
        cityTextField.setText(customer.getPostAddress());
    }
    
    private boolean saveUserInfo() {
        String persnbr = persnbrTextField.getText();
        
        String address = adressTextField.getText();
        String email = emailTextField.getText();
        String firstname = prenameTextField.getText();
        String lastname = lastnameTextField.getText();
        String phoneNumber = phoneTextField.getText();
        String city = cityTextField.getText();
        String postCode = postadressTextField.getText();

        String oldPassword = new String(oldpasswrdField.getPassword());
        String newPassword = new String(newpasswrdField.getPassword());
        
        um.updateInfo(persnbr, address, email, firstname, lastname, phoneNumber, city, postCode);
        
        if (!(oldPassword.equals("") && newPassword.equals(""))) {
            if (um.getPassword().equals(oldPassword)) {
                um.setPassword(newPassword);
            } else {
                oldpasswrdLabel.setForeground(Constants.ERROR_COLOR);
                return false;
            }
        }
        
        return true;
    }
    
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals("updateInfo")) {
            prefillForm();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prenameLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        lastnameTextField = new javax.swing.JTextField();
        ephoneLabel = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        oldpasswrdLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        newpasswrdLabel = new javax.swing.JLabel();
        eEmailLabel = new javax.swing.JLabel();
        oldpasswrdField = new javax.swing.JPasswordField();
        adressTextField = new javax.swing.JTextField();
        newpasswrdField = new javax.swing.JPasswordField();
        eadressLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        eheadLabel = new javax.swing.JLabel();
        postadressTextField = new javax.swing.JTextField();
        persnbrTextField = new javax.swing.JTextField();
        epostadressLabel = new javax.swing.JLabel();
        epersnbrLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        prenameTextField = new javax.swing.JTextField();
        ecityLabel = new javax.swing.JLabel();

        prenameLabel.setText("Förnamn:");

        ephoneLabel.setText("Mobilnr:");

        lastnameLabel.setText("Efternamn:");

        oldpasswrdLabel.setText("Gammalt lösenord:");

        newpasswrdLabel.setText("Nytt Lösenord:");

        eEmailLabel.setText("E-postadress: ");

        eadressLabel.setText("Gatuadress:");

        saveButton.setText("Spara ändringar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        eheadLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        eheadLabel.setText("Kontaktupgifter");

        epostadressLabel.setText("Postnummer:");

        epersnbrLabel.setText("Pers.nr:");

        ecityLabel.setBackground(new java.awt.Color(255, 255, 255));
        ecityLabel.setText("Stad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(eheadLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(epersnbrLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(eEmailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(prenameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(eadressLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ephoneLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lastnameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(epostadressLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ecityLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(oldpasswrdLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(newpasswrdLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(prenameTextField)
                            .addComponent(lastnameTextField)
                            .addComponent(emailTextField)
                            .addComponent(adressTextField)
                            .addComponent(postadressTextField)
                            .addComponent(cityTextField)
                            .addComponent(phoneTextField)
                            .addComponent(persnbrTextField)
                            .addComponent(oldpasswrdField, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(newpasswrdField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eheadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(epersnbrLabel)
                            .addComponent(persnbrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prenameLabel)
                            .addComponent(prenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnameLabel)
                            .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eEmailLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eadressLabel)
                            .addComponent(adressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(epostadressLabel)
                            .addComponent(postadressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ecityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ephoneLabel)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(oldpasswrdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oldpasswrdLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpasswrdLabel)
                    .addComponent(newpasswrdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (saveUserInfo()) {
            oldpasswrdField.setText("");
            newpasswrdField.setText("");
            firePropertyChange("showProfileCard", null, null);
        }
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adressTextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel eEmailLabel;
    private javax.swing.JLabel eadressLabel;
    private javax.swing.JLabel ecityLabel;
    private javax.swing.JLabel eheadLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel epersnbrLabel;
    private javax.swing.JLabel ephoneLabel;
    private javax.swing.JLabel epostadressLabel;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JPasswordField newpasswrdField;
    private javax.swing.JLabel newpasswrdLabel;
    private javax.swing.JPasswordField oldpasswrdField;
    private javax.swing.JLabel oldpasswrdLabel;
    private javax.swing.JTextField persnbrTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField postadressTextField;
    private javax.swing.JLabel prenameLabel;
    private javax.swing.JTextField prenameTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
